# Homework 3

In this homework, we will use the 2026 lead-scoring data.

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as  plt

In [2]:
data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv'

In [3]:
!wget $data -O homework-data-week-3.csv

--2026-09-28 12:15:38--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 278746 (272K) [text/plain]
Saving to: ‘homework-data-week-3.csv’

homework-data-week- 100%[===================>] 272.21K  --.-KB/s    in 0.006s

2026-09-28 12:15:38 (45.9 MB/s) - ‘homework-data-week-3.csv’ saved [278746/278746]

In [4]:
df = pd.read_csv('homework-data-week-3.csv')
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NaN,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

In [5]:
df.columns

Index(['lead_source', 'industry', 'employment_status', 'location',
       'annual_income', 'number_of_courses_viewed', 'interaction_count',
       'lead_score', 'converted'],
      dtype='str')

In [6]:
for col in df.columns:
    print(col)
    print(df[col].unique()[:7])
    print(df[col].nunique())
    print()

lead_source
<StringArray>
['organic_search', 'social_media', 'referral', 'paid_ads', nan, 'events']
Length: 6, dtype: str
5

industry
<StringArray>
[   'technology',        'retail', 'manufacturing',     'education',
    'healthcare',             nan,       'finance']
Length: 7, dtype: str
6

employment_status
<StringArray>
['employed', 'student', nan, 'unemployed', 'self_employed']
Length: 5, dtype: str
4

location
<StringArray>
['europe', 'south_america', nan, 'north_america', 'africa', 'asia']
Length: 6, dtype: str
5

annual_income
[88160. 72688. 44697.    nan 24062. 43841. 58738.]
4313

number_of_courses_viewed
[3 4 2 1 0 5 6]
7

interaction_count
[4 7 6 5 9 2 0]
14

lead_score
[0.64 0.72 0.58 0.57 0.62 0.77 0.78]
99

converted
[1 0]
2

In [7]:
categorical =['lead_source', 'industry', 'employment_status', 'location']

In [8]:
numerical = ['annual_income', 'number_of_courses_viewed', 'interaction_count',
       'lead_score']

In [9]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [10]:
df[categorical]

         lead_source       industry employment_status       location
0     organic_search     technology          employed         europe
1       social_media     technology          employed  south_america
2           referral         retail          employed         europe
3           paid_ads  manufacturing           student            NaN
4           referral  manufacturing           student  north_america
...              ...            ...               ...            ...
4995  organic_search      education          employed           asia
4996             NaN     technology          employed  north_america
4997  organic_search        finance          employed           asia
4998        referral     technology          employed         africa
4999        referral     technology          employed         europe

[5000 rows x 4 columns]

In [11]:
df[categorical].isnull().sum()

lead_source          148
industry             240
employment_status    194
location             208
dtype: int64

In [12]:
df[categorical] = df[categorical].fillna('NA')

In [13]:
df[categorical]

         lead_source       industry employment_status       location
0     organic_search     technology          employed         europe
1       social_media     technology          employed  south_america
2           referral         retail          employed         europe
3           paid_ads  manufacturing           student             NA
4           referral  manufacturing           student  north_america
...              ...            ...               ...            ...
4995  organic_search      education          employed           asia
4996              NA     technology          employed  north_america
4997  organic_search        finance          employed           asia
4998        referral     technology          employed         africa
4999        referral     technology          employed         europe

[5000 rows x 4 columns]

In [14]:
df[numerical] = df[numerical].fillna(0)

In [15]:
df[numerical]

      annual_income  number_of_courses_viewed  interaction_count  lead_score
0           88160.0                         3                  4        0.64
1           72688.0                         3                  7        0.72
2           44697.0                         3                  4        0.58
3               0.0                         3                  6        0.57
4           24062.0                         4                  5        0.62
...             ...                       ...                ...         ...
4995        45834.0                         2                  2        0.37
4996        84831.0                         2                  5        0.51
4997        53636.0                         4                  6        0.75
4998        69430.0                         4                  8        0.79
4999        81355.0                         6                 11        0.99

[5000 rows x 4 columns]

In [16]:
mode = df['industry'].mode()[0]

print(f"The most frequent observation in the industry column is: {mode}")

The most frequent observation in the industry column is: technology

In [17]:
df['industry'].value_counts()[mode]  #Check the number of times it appears

np.int64(1173)

In [18]:
for c in df['industry'].unique():
    freq = df['industry'].value_counts()[c]

    print(c, freq)

technology 1173
retail 925
manufacturing 463
education 639
healthcare 840
NA 240
finance 720

In [20]:
df[numerical].corr()

,annual_income,number_of_courses_viewed,interaction_count,lead_score
annual_income,1.000000,0.161300,0.122842,0.229496
number_of_courses_viewed,0.161300,1.000000,0.721609,0.757204
interaction_count,0.122842,0.721609,1.000000,0.915746
lead_score,0.229496,0.757204,0.915746,1.000000

In [21]:
df[numerical].corr().

annual_income               1.0
number_of_courses_viewed    1.0
interaction_count           1.0
lead_score                  1.0
dtype: float64